### ISSUE TITLE
healthbar in entities

### ISSUE THREAD

**Issue by BlockCat** [Arkarstronk/TurnBasedFeest#1]
https://github.com/Arkarstronk/TurnBasedFeest/blob/e5008a4dfdd12d801d93ebbe1410c9619ce2a3ca/Entities/Entity.cs#L30

I think healthbars should be extracted to become their own class, 
makes it easier to change later on too.

**Comment by BlockCat** [comment]
also, those entities smell like inheritance, but the popular belief lately is to move away from inheritance to composition.
https://en.wikipedia.org/wiki/Composition_over_inheritance

**Comment by Arkarstronk** [comment]
Every entity will have a healthbar though, maybe I shouldn't have called it "entity"?
