### ISSUE TITLE
Player attributes have to be made

### ISSUE THREAD

**Issue by Arkarstronk** [Arkarstronk/TurnBasedFeest#18]
A simple mechanism has to be in place to make the defend action for example work

**Comment by BlockCat** [comment]
Can i take this one?

**Comment by Arkarstronk** [comment]
Sure, but no skills/levels yet, only something that can store action-afflicted attributes

**Comment by BlockCat** [comment]
with skills you mean: Actions like Attack, Defend, Magic right?

and action-afflicted attributes are for states like: defending, poisoned, dead, turned-into-a-frog etc right?

**Comment by Arkarstronk** [comment]
yup
